/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.management.system;

 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Aayush Kanholikar
 */
public class StudentRegister extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 0, 50)); // NOI18N
        jLabel1.setText("Student Registration");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel3.setText("Roll No.");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel4.setText("Branch");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String Name=jTextField1.getText();
        String Rollno=jTextField2.getText();
        String Branch=jTextField3.getText();
        String Address=jTextField4.getText();
        String Phone=jTextField5.getText();
        String Email=jTextField6.getText();
        String Password=jTextField7.getText();
        
        
        
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()
                ||jTextField6.getText().isEmpty()||jTextField7.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please fill all information correctly!!!\n"+"Every Field is Requried!!!");
            this.setVisible(true);
        }
        else
        {

try
    {
Class.forName("java.sql.DriverManager");
Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
Statement stmt = (Statement) con.createStatement();
String query="INSERT INTO Students VALUES('"+Name+"','"+Rollno+"','"+Branch+"','"+Address+"','"+Phone+"','"+Email+"','"+Password+"');";
stmt.executeUpdate(query);
JOptionPane.showMessageDialog (this, "Resgistration Successful!!!!");
this.setVisible(false);
        TeacherStartPage tsp = new TeacherStartPage();
        tsp.setVisible(true);


}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
}

try
    {
Class.forName("java.sql.DriverManager");
Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
Statement stmt = (Statement) con.createStatement();
String query="insert into percentage values('"+Name+"',0,0,0,0,0,0);";
stmt.executeUpdate(query);

}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
}
 
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
         this.setVisible(false);
        TeacherStartPage tsp = new TeacherStartPage();
        tsp.setVisible(true);
        
        
        PreparedStatement pst;
        ResultSet rs;
        
       
        try
    {
Class.forName("java.sql.DriverManager");
Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
Statement stmt = (Statement) con.createStatement();


           String Query ="select * from attendance_status where srno='1';";
            rs=stmt.executeQuery(Query); 
            int i=0;    
            while(rs.next())
            { 
                i++;
            TeacherStartPage.jTextField1.setText(rs.getString("Status"));     }
         
            



}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
} 
         try
    {
Class.forName("java.sql.DriverManager");
Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
Statement stmt = (Statement) con.createStatement();


           String Query ="select * from attendance_status where srno='1';";
            rs=stmt.executeQuery(Query); 
            int i=0;    
            while(rs.next())
            { 
                i++;
            TeacherStartPage.jTextField2.setText(rs.getString("Subject"));     }
         
           



}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
}
         String status = TeacherStartPage.jTextField1.getText();
         if(status.equals("DEACTIVATE"))
        {
            TeacherStartPage.jLabel4.setVisible(false); 
            TeacherStartPage.jTextField2.setVisible(false);
            jTextField2.setVisible(false);
jLabel4.setVisible(false);
TeacherStartPage.jCheckBox1.setEnabled(false);
TeacherStartPage.jCheckBox2.setEnabled(false);
TeacherStartPage.jCheckBox3.setEnabled(false);
TeacherStartPage.jCheckBox4.setEnabled(false);
TeacherStartPage.jCheckBox5.setEnabled(false);
TeacherStartPage.jCheckBox6.setEnabled(false);
        } else
        {
           TeacherStartPage.jLabel4.setVisible(true); 
            TeacherStartPage.jTextField2.setVisible(true);
            jTextField2.setVisible(true);
jLabel4.setVisible(true);
TeacherStartPage.jCheckBox1.setEnabled(true);
TeacherStartPage.jCheckBox2.setEnabled(true);
TeacherStartPage.jCheckBox3.setEnabled(true);
TeacherStartPage.jCheckBox4.setEnabled(true);
TeacherStartPage.jCheckBox5.setEnabled(true);
TeacherStartPage.jCheckBox6.setEnabled(true); 
        }

String subject = TeacherStartPage.jTextField2.getText();
if(subject.equals("EM"))
{
    TeacherStartPage.jCheckBox1.setSelected(true);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("EIM"))
{
   TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(true);
    TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("EDC"))
{
    TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
    TeacherStartPage.jCheckBox3.setSelected(true);
    TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("DLC"))
{
   TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
    TeacherStartPage.jCheckBox4.setSelected(true);
    TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("ENAS"))
{
    TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
    TeacherStartPage.jCheckBox5.setSelected(true);
    TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("SBL"))
{
    TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
    TeacherStartPage.jCheckBox6.setSelected(true);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
