/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.management.system;


import static attendance.management.system.TeacherStartPage.jLabel4;
import static attendance.management.system.TeacherStartPage.jTextField2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Aayush Kanholikar
 */
public class TeacherLogin extends javax.swing.JFrame {

    /**
     * Creates new form TeacherLogin
     */
    public TeacherLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 0, 50)); // NOI18N
        jLabel1.setText("Teacher Login");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel4.setText("Don't Have Account");

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TeacherRegister tr = new TeacherRegister();
        tr.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StartPage sp=new StartPage();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst;
        ResultSet rs;
        
        String Name = jTextField1.getText();
        String Password = String.valueOf(jPasswordField1.getPassword());
             
        try
    {
Class.forName("java.sql.DriverManager");
Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
Statement stmt = (Statement) con.createStatement();
String Query = "SELECT * FROM Teachers WHERE name = ? AND Password = ?";
        pst= con.prepareStatement(Query);
        pst.setString(1, Name);
        pst.setString(2, Password);
        rs = pst.executeQuery();
        
        if(rs.next()){  
            JOptionPane.showMessageDialog (this, "Login Successfull");
          this.setVisible(false);
        TeacherStartPage tsp = new TeacherStartPage();
        tsp.setVisible(true);
       
        try
    {
Class.forName("java.sql.DriverManager");

            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
 stmt = (Statement) con.createStatement();


            Query ="select * from attendance_status where srno='1';";
            rs=stmt.executeQuery(Query); 
            int i=0;    
            while(rs.next())
            { 
                i++;
            TeacherStartPage.jTextField1.setText(rs.getString("Status"));     }
         
            if(i==0)
            { TeacherStartPage.jTextField1.setText("");  } 



}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
}
        
        try
    {
Class.forName("java.sql.DriverManager");

            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","9970727628");
 stmt = (Statement) con.createStatement();


            Query ="select * from attendance_status where srno='1';";
            rs=stmt.executeQuery(Query); 
            int i=0;    
            while(rs.next())
            { 
                i++;
            TeacherStartPage.jTextField2.setText(rs.getString("Subject"));     }
         
            if(i==0)
            { TeacherStartPage.jTextField2.setText("");  } 



}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
}
     String status = TeacherStartPage.jTextField1.getText();  if(status.equals("DEACTIVATE"))
        {
            TeacherStartPage.jLabel4.setVisible(false); 
            TeacherStartPage.jTextField2.setVisible(false);
            jTextField2.setVisible(false);
jLabel4.setVisible(false);
TeacherStartPage.jCheckBox1.setEnabled(false);
TeacherStartPage.jCheckBox2.setEnabled(false);
TeacherStartPage.jCheckBox3.setEnabled(false);
TeacherStartPage.jCheckBox4.setEnabled(false);
TeacherStartPage.jCheckBox5.setEnabled(false);
TeacherStartPage.jCheckBox6.setEnabled(false);
        } 
        else
        {
           TeacherStartPage.jLabel4.setVisible(true); 
            TeacherStartPage.jTextField2.setVisible(true);
            jTextField2.setVisible(true);
jLabel4.setVisible(true);
TeacherStartPage.jCheckBox1.setEnabled(true);
TeacherStartPage.jCheckBox2.setEnabled(true);
TeacherStartPage.jCheckBox3.setEnabled(true);
TeacherStartPage.jCheckBox4.setEnabled(true);
TeacherStartPage.jCheckBox5.setEnabled(true);
TeacherStartPage.jCheckBox6.setEnabled(true); 

String subject = TeacherStartPage.jTextField2.getText();
if(subject.equals("EM"))
{
    TeacherStartPage.jCheckBox1.setSelected(true);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("EIM"))
{
   TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(true);
    TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("EDC"))
{
    TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
    TeacherStartPage.jCheckBox3.setSelected(true);
    TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("DLC"))
{
   TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
    TeacherStartPage.jCheckBox4.setSelected(true);
    TeacherStartPage.jCheckBox5.setSelected(false);
TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("ENAS"))
{
    TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
    TeacherStartPage.jCheckBox5.setSelected(true);
    TeacherStartPage.jCheckBox6.setSelected(false);
}
else if(subject.equals("SBL"))
{
    TeacherStartPage.jCheckBox1.setSelected(false);
    TeacherStartPage.jCheckBox2.setSelected(false);
TeacherStartPage.jCheckBox3.setSelected(false);
TeacherStartPage.jCheckBox4.setSelected(false);
TeacherStartPage.jCheckBox5.setSelected(false);
    TeacherStartPage.jCheckBox6.setSelected(true);
}
        }
        
        
        }
        else{
        JOptionPane.showMessageDialog(null,"Incorrect username Or Password ! ");
         jTextField1.setText("");
        jPasswordField1.setText("");
        
        }  
}
catch(Exception e)

{

JOptionPane.showMessageDialog (this, e.getMessage());
}
        
        
        
        
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
